/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package travel_agency;

import com.mysql.cj.protocol.Resultset;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author admin
 */
public class BranchMenu extends javax.swing.JFrame {
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;

    /**
     * Creates new form BranchMenu
     */
    public BranchMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Br_code", "Street", "Number", "City", "M_Name", "M_Lastname"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel2.setText("Choose Branch for information:");

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Choose Branch for Employees info:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Br_code", "Emp_Name", "Emp_Lastname", "Salary"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Branch 1", "Branch 2", "Branch 3", "Branch 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Branch 1", "Branch 2", "Branch 3", "Branch 4" }));

        jButton11.setText("Show Branch Info");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Show Employees info");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel3.setText("Choose for insert/delete/update any of these tables :");

        jButton2.setText("Branch");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Employee");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(301, 301, 301))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(278, 278, 278))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton12)
                        .addGap(181, 181, 181))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addComponent(jButton2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addGap(226, 226, 226))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(14, 14, 14)
                        .addComponent(jButton11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
       Login log=new Login();
       log.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       this.dispose();
       MENU_IT mn=new MENU_IT();
       mn.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        DefaultTableModel mytbl = (DefaultTableModel) jTable1.getModel();
        mytbl.setRowCount(0);
        conn=DBconnection.ConnectDB();
        String branch=jComboBox1.getSelectedItem().toString();
        String myquery="SELECT mng_br_code,br_street,br_num,br_city,wrk_name,wrk_lname FROM manages INNER JOIN branch ON mng_br_code=br_code INNER JOIN admin ON mng_adm_AT=adm_AT INNER JOIN worker ON adm_AT=wrk_AT WHERE mng_br_code=1";
        String myquery1="SELECT mng_br_code,br_street,br_num,br_city,wrk_name,wrk_lname FROM manages INNER JOIN branch ON mng_br_code=br_code INNER JOIN admin ON mng_adm_AT=adm_AT INNER JOIN worker ON adm_AT=wrk_AT WHERE mng_br_code=2";
        String myquery2="SELECT mng_br_code,br_street,br_num,br_city,wrk_name,wrk_lname FROM manages INNER JOIN branch ON mng_br_code=br_code INNER JOIN admin ON mng_adm_AT=adm_AT INNER JOIN worker ON adm_AT=wrk_AT WHERE mng_br_code=3";
        String myquery3="SELECT mng_br_code,br_street,br_num,br_city,wrk_name,wrk_lname FROM manages INNER JOIN branch ON mng_br_code=br_code INNER JOIN admin ON mng_adm_AT=adm_AT INNER JOIN worker ON adm_AT=wrk_AT WHERE mng_br_code=4";
        
        try{
        
            switch(branch){
                case "Branch 1":
                  pst=conn.prepareStatement(myquery);
                  rs= pst.executeQuery();
                 
              while(rs.next()){
              int bc = rs.getInt("mng_br_code");
              String mng_br_code=String.valueOf(bc);
              String br_street=rs.getString("br_street");
              int bn = rs.getInt("br_num");
              String br_num=String.valueOf(bn);
              String br_city=rs.getString("br_city");
              String wrk_name=rs.getString("wrk_name");
              String wrk_lname=rs.getString("wrk_lname");
              
              String table1[]={mng_br_code,br_street,br_num,br_city,wrk_name,wrk_lname};
              mytbl.addRow(table1);
              }
              break;
              
                case "Branch 2":
                    pst=conn.prepareStatement(myquery1);
          rs= pst.executeQuery();
          while(rs.next()){
              int bc = rs.getInt("mng_br_code");
              String mng_br_code=String.valueOf(bc);
              String br_street=rs.getString("br_street");
              int bn = rs.getInt("br_num");
              String br_num=String.valueOf(bn);
              String br_city=rs.getString("br_city");
              String wrk_name=rs.getString("wrk_name");
              String wrk_lname=rs.getString("wrk_lname");
              
              String table1[]={mng_br_code,br_street,br_num,br_city,wrk_name,wrk_lname};
              mytbl.addRow(table1);
              }
          break;
          
                case "Branch 3":
                    pst=conn.prepareStatement(myquery2);
          rs= pst.executeQuery();
          while(rs.next()){
              int bc = rs.getInt("mng_br_code");
              String mng_br_code=String.valueOf(bc);
              String br_street=rs.getString("br_street");
              int bn = rs.getInt("br_num");
              String br_num=String.valueOf(bn);
              String br_city=rs.getString("br_city");
              String wrk_name=rs.getString("wrk_name");
              String wrk_lname=rs.getString("wrk_lname");
              
              String table1[]={mng_br_code,br_street,br_num,br_city,wrk_name,wrk_lname};
              mytbl.addRow(table1);
              }
          break;
          
          case"Branch 4":
               pst=conn.prepareStatement(myquery3);
          rs= pst.executeQuery();
          while(rs.next()){
              int bc = rs.getInt("mng_br_code");
              String mng_br_code=String.valueOf(bc);
              String br_street=rs.getString("br_street");
              int bn = rs.getInt("br_num");
              String br_num=String.valueOf(bn);
              String br_city=rs.getString("br_city");
              String wrk_name=rs.getString("wrk_name");
              String wrk_lname=rs.getString("wrk_lname");
              
              String table1[]={mng_br_code,br_street,br_num,br_city,wrk_name,wrk_lname};
              mytbl.addRow(table1);
              }
             break;
              
                    
                    
            
            }
        }
             catch(SQLException ex){
             JOptionPane.showMessageDialog(null,ex);  
                    
        
        }
        
        
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        DefaultTableModel mytbl = (DefaultTableModel) jTable2.getModel();
        mytbl.setRowCount(0);
        conn=DBconnection.ConnectDB(); 
        String branch=jComboBox2.getSelectedItem().toString();
        String myquery="SELECT br_code,wrk_name,wrk_lname,wrk_salary FROM worker INNER JOIN branch ON wrk_br_code=br_code WHERE br_code=1";
        String myquery1="SELECT br_code,wrk_name,wrk_lname,wrk_salary FROM worker INNER JOIN branch ON wrk_br_code=br_code WHERE br_code=2";
        String myquery2="SELECT br_code,wrk_name,wrk_lname,wrk_salary FROM worker INNER JOIN branch ON wrk_br_code=br_code WHERE br_code=3";
        String myquery3="SELECT br_code,wrk_name,wrk_lname,wrk_salary FROM worker INNER JOIN branch ON wrk_br_code=br_code WHERE br_code=4";
        
        
         try{
        
             switch(branch){
                case "Branch 1":
                pst=conn.prepareStatement(myquery);
                rs= pst.executeQuery();
         
                while(rs.next()){
              int bc = rs.getInt("br_code");
              String br_code=String.valueOf(bc);
              String wrk_name=rs.getString("wrk_name");
              String wrk_lname=rs.getString("wrk_lname");
              double ws = rs.getDouble("wrk_salary");
              String wrk_salary=String.valueOf(ws);
              
              
             
             
             
              
              String table1[]={br_code,wrk_name,wrk_lname,wrk_salary};
              mytbl.addRow(table1);
              }
             
               break;      
             
              
                
                 
              case "Branch 2":
                 
                  pst=conn.prepareStatement(myquery1);
                  rs= pst.executeQuery();
              
             while(rs.next()){
              int bc = rs.getInt("br_code");
              String br_code=String.valueOf(bc);
              String wrk_name=rs.getString("wrk_name");
              String wrk_lname=rs.getString("wrk_lname");
              double ws = rs.getDouble("wrk_salary");
              String wrk_salary=String.valueOf(ws);
              
              
             
             
             
              
              String table1[]={br_code,wrk_name,wrk_lname,wrk_salary};
              mytbl.addRow(table1);
              }
              break;
              
             case "Branch 3":
                pst=conn.prepareStatement(myquery2);
                rs= pst.executeQuery();
             
                while(rs.next()){
              int bc = rs.getInt("br_code");
              String br_code=String.valueOf(bc);
              String wrk_name=rs.getString("wrk_name");
              String wrk_lname=rs.getString("wrk_lname");
              double ws = rs.getDouble("wrk_salary");
              String wrk_salary=String.valueOf(ws);
              
              
             
             
             
              
              String table1[]={br_code,wrk_name,wrk_lname,wrk_salary};
              mytbl.addRow(table1);
              }
             break;
          
              case "Branch 4":
                pst=conn.prepareStatement(myquery3);
                rs= pst.executeQuery();
         
                while(rs.next()){
              int bc = rs.getInt("br_code");
              String br_code=String.valueOf(bc);
              String wrk_name=rs.getString("wrk_name");
              String wrk_lname=rs.getString("wrk_lname");
              double ws = rs.getDouble("wrk_salary");
              String wrk_salary=String.valueOf(ws);
              
              
             
             
             
              
              String table1[]={br_code,wrk_name,wrk_lname,wrk_salary};
              mytbl.addRow(table1);
              }
              break;
               
                 
                 
              
               
                    
            
            }
         }
         
             catch(SQLException ex){
             JOptionPane.showMessageDialog(null,ex);  
                    
                     }
        
            
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        BranchUpdate bu=new BranchUpdate();
        bu.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        EmployeeUpdate eu=new EmployeeUpdate();
        eu.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BranchMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BranchMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BranchMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BranchMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BranchMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
