/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package travel_agency;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author admin
 */
public class BranchMenu extends javax.swing.JFrame {
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    private String currentUser;
    /**
     * Creates new form BranchMenu
     */
    public BranchMenu() {
        initComponents();
    }
    
     public BranchMenu(String currentUser) {
        initComponents();
        this.currentUser = currentUser;
    }
     
      public String getUser() {
        return this.currentUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Br_code", "Street", "Number", "City", "M_Name", "M_Lastname"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel2.setText("Choose Branch for information:");

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Choose Branch for Employees info:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Br_code", "Emp_Name", "Emp_Lastname", "Salary"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Branch 1", "Branch 2", "Branch 3", "Branch 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Branch 1", "Branch 2", "Branch 3", "Branch 4" }));

        jButton11.setText("Show info");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Show info");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel3.setText("Choose for insert/delete/update any of these tables :");

        jButton2.setText("Branch");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Employee");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Total salary expenses :");

        jLabel5.setText("Total reservations :");

        jLabel6.setText("Total incomes from reservations :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(197, 197, 197)
                                    .addComponent(jButton11))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jButton12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addComponent(jButton2))
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
       Login log=new Login();
       log.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       this.dispose();
       MENU_IT mn=new MENU_IT();
       mn.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        DefaultTableModel mytbl = (DefaultTableModel) jTable1.getModel();
        mytbl.setRowCount(0);
        conn=DBconnection.ConnectDB();
        String branch=jComboBox1.getSelectedItem().toString();
        String myquery="SELECT mng_br_code,br_street,br_num,br_city,wrk_name,wrk_lname FROM manages INNER JOIN branch ON mng_br_code=br_code INNER JOIN admin ON mng_adm_AT=adm_AT INNER JOIN worker ON adm_AT=wrk_AT WHERE mng_br_code=1";
        String myquery1="SELECT mng_br_code,br_street,br_num,br_city,wrk_name,wrk_lname FROM manages INNER JOIN branch ON mng_br_code=br_code INNER JOIN admin ON mng_adm_AT=adm_AT INNER JOIN worker ON adm_AT=wrk_AT WHERE mng_br_code=2";
        String myquery2="SELECT mng_br_code,br_street,br_num,br_city,wrk_name,wrk_lname FROM manages INNER JOIN branch ON mng_br_code=br_code INNER JOIN admin ON mng_adm_AT=adm_AT INNER JOIN worker ON adm_AT=wrk_AT WHERE mng_br_code=3";
        String myquery3="SELECT mng_br_code,br_street,br_num,br_city,wrk_name,wrk_lname FROM manages INNER JOIN branch ON mng_br_code=br_code INNER JOIN admin ON mng_adm_AT=adm_AT INNER JOIN worker ON adm_AT=wrk_AT WHERE mng_br_code=4";
        
        try{
        
            switch(branch){
                case "Branch 1":
                  pst=conn.prepareStatement(myquery);
                  rs= pst.executeQuery();
                 
              while(rs.next()){
              int bc = rs.getInt("mng_br_code");
              String mng_br_code=String.valueOf(bc);
              String br_street=rs.getString("br_street");
              int bn = rs.getInt("br_num");
              String br_num=String.valueOf(bn);
              String br_city=rs.getString("br_city");
              String wrk_name=rs.getString("wrk_name");
              String wrk_lname=rs.getString("wrk_lname");
              
              String table1[]={mng_br_code,br_street,br_num,br_city,wrk_name,wrk_lname};
              mytbl.addRow(table1);
              }
              break;
              
                case "Branch 2":
                    pst=conn.prepareStatement(myquery1);
          rs= pst.executeQuery();
          while(rs.next()){
              int bc = rs.getInt("mng_br_code");
              String mng_br_code=String.valueOf(bc);
              String br_street=rs.getString("br_street");
              int bn = rs.getInt("br_num");
              String br_num=String.valueOf(bn);
              String br_city=rs.getString("br_city");
              String wrk_name=rs.getString("wrk_name");
              String wrk_lname=rs.getString("wrk_lname");
              
              String table1[]={mng_br_code,br_street,br_num,br_city,wrk_name,wrk_lname};
              mytbl.addRow(table1);
              }
          break;
          
                case "Branch 3":
                    pst=conn.prepareStatement(myquery2);
          rs= pst.executeQuery();
          while(rs.next()){
              int bc = rs.getInt("mng_br_code");
              String mng_br_code=String.valueOf(bc);
              String br_street=rs.getString("br_street");
              int bn = rs.getInt("br_num");
              String br_num=String.valueOf(bn);
              String br_city=rs.getString("br_city");
              String wrk_name=rs.getString("wrk_name");
              String wrk_lname=rs.getString("wrk_lname");
              
              String table1[]={mng_br_code,br_street,br_num,br_city,wrk_name,wrk_lname};
              mytbl.addRow(table1);
              }
          break;
          
          case"Branch 4":
               pst=conn.prepareStatement(myquery3);
          rs= pst.executeQuery();
          while(rs.next()){
              int bc = rs.getInt("mng_br_code");
              String mng_br_code=String.valueOf(bc);
              String br_street=rs.getString("br_street");
              int bn = rs.getInt("br_num");
              String br_num=String.valueOf(bn);
              String br_city=rs.getString("br_city");
              String wrk_name=rs.getString("wrk_name");
              String wrk_lname=rs.getString("wrk_lname");
              
              String table1[]={mng_br_code,br_street,br_num,br_city,wrk_name,wrk_lname};
              mytbl.addRow(table1);
              }
             break;
              
                    
                    
            
            }
        }
             catch(SQLException ex){
             JOptionPane.showMessageDialog(null,ex);  
                    
        
        }
        
        
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        DefaultTableModel mytbl = (DefaultTableModel) jTable2.getModel();
        mytbl.setRowCount(0);
        conn=DBconnection.ConnectDB(); 
        String branch=jComboBox2.getSelectedItem().toString();
        ResultSet rs1;
        ResultSet rs2;
        ResultSet rs3;
        
        
        String myquery="SELECT br_code,wrk_name,wrk_lname,wrk_salary FROM worker INNER JOIN branch ON wrk_br_code=br_code WHERE br_code=1";
        String myquery1="SELECT br_code,wrk_name,wrk_lname,wrk_salary FROM worker INNER JOIN branch ON wrk_br_code=br_code WHERE br_code=2";
        String myquery2="SELECT br_code,wrk_name,wrk_lname,wrk_salary FROM worker INNER JOIN branch ON wrk_br_code=br_code WHERE br_code=3";
        String myquery3="SELECT br_code,wrk_name,wrk_lname,wrk_salary FROM worker INNER JOIN branch ON wrk_br_code=br_code WHERE br_code=4";
        String myquery4="SELECT SUM(wrk_salary) AS total_expenses FROM worker WHERE wrk_br_code=1";
        String myquery5="SELECT SUM(wrk_salary) AS total_expenses FROM worker WHERE wrk_br_code=2";
        String myquery6="SELECT SUM(wrk_salary) AS total_expenses FROM worker WHERE wrk_br_code=3";
        String myquery7="SELECT SUM(wrk_salary) AS total_expenses FROM worker WHERE wrk_br_code=4";
        String myquery8="SELECT SUM(total) AS total_reservations FROM (SELECT COUNT(reservation.res_tr_id) AS total FROM reservation INNER JOIN trip ON reservation.res_tr_id = trip.tr_id INNER JOIN branch ON trip.tr_br_code = branch.br_code WHERE branch.br_code = 1 GROUP BY reservation.res_tr_id) AS subquery"; 
        String myquery9="SELECT SUM(total) AS total_reservations FROM (SELECT COUNT(reservation.res_tr_id) AS total FROM reservation INNER JOIN trip ON reservation.res_tr_id = trip.tr_id INNER JOIN branch ON trip.tr_br_code = branch.br_code WHERE branch.br_code = 2 GROUP BY reservation.res_tr_id) AS subquery"; 
        String myquery10="SELECT SUM(total) AS total_reservations FROM (SELECT COUNT(reservation.res_tr_id) AS total FROM reservation INNER JOIN trip ON reservation.res_tr_id = trip.tr_id INNER JOIN branch ON trip.tr_br_code = branch.br_code WHERE branch.br_code = 3 GROUP BY reservation.res_tr_id) AS subquery"; 
        String myquery11="SELECT SUM(total) AS total_reservations FROM (SELECT COUNT(reservation.res_tr_id) AS total FROM reservation INNER JOIN trip ON reservation.res_tr_id = trip.tr_id INNER JOIN branch ON trip.tr_br_code = branch.br_code WHERE branch.br_code = 4 GROUP BY reservation.res_tr_id) AS subquery"; 
        String myquery12="SELECT SUM(total) AS total_incomes FROM(SELECT COUNT(res_tr_id) * tr_cost AS total FROM  reservation INNER JOIN trip ON res_tr_id=tr_id INNER JOIN branch ON tr_br_code=br_code WHERE br_code=1 GROUP BY res_tr_id )AS subquery"; 
        String myquery13="SELECT SUM(total) AS total_incomes FROM(SELECT COUNT(res_tr_id) * tr_cost AS total FROM  reservation INNER JOIN trip ON res_tr_id=tr_id INNER JOIN branch ON tr_br_code=br_code WHERE br_code=2 GROUP BY res_tr_id )AS subquery";
        String myquery14="SELECT SUM(total) AS total_incomes FROM(SELECT COUNT(res_tr_id) * tr_cost AS total FROM  reservation INNER JOIN trip ON res_tr_id=tr_id INNER JOIN branch ON tr_br_code=br_code WHERE br_code=3 GROUP BY res_tr_id )AS subquery"; 
        String myquery15="SELECT SUM(total) AS total_incomes FROM(SELECT COUNT(res_tr_id) * tr_cost AS total FROM  reservation INNER JOIN trip ON res_tr_id=tr_id INNER JOIN branch ON tr_br_code=br_code WHERE br_code=4 GROUP BY res_tr_id )AS subquery";  
        try{
        
             switch(branch){
                case "Branch 1":
                pst=conn.prepareStatement(myquery);
                rs= pst.executeQuery();
         
                while(rs.next()){
              int bc = rs.getInt("br_code");
              String br_code=String.valueOf(bc);
              String wrk_name=rs.getString("wrk_name");
              String wrk_lname=rs.getString("wrk_lname");
              double ws = rs.getDouble("wrk_salary");
              String wrk_salary=String.valueOf(ws);
              
              
             
             
             
              
              String table1[]={br_code,wrk_name,wrk_lname,wrk_salary};
              mytbl.addRow(table1);
              
               pst=conn.prepareStatement(myquery4);
               rs1=pst.executeQuery();
               if (rs1.next()) {
                
                String expenses = rs1.getString("total_expenses");
                jTextField1.setText(expenses);
                jTextField1.setEditable(false);
            } else {
                jTextField1.setText("No data found");
            }
               
               pst=conn.prepareStatement(myquery8);
               rs2=pst.executeQuery();
               if (rs2.next()) {
                
                String totalres = rs2.getString("total_reservations");
                jTextField2.setText(totalres);
                jTextField2.setEditable(false);
            } else {
                jTextField2.setText("No reservations found");
            }
               
              pst=conn.prepareStatement(myquery12);
               rs3=pst.executeQuery();
               if (rs3.next()) {
                
                String totalres = rs3.getString("total_incomes");
                jTextField3.setText(totalres);
                jTextField3.setEditable(false);
            } else {
                jTextField3.setText("No incomes found");
            } 
                
                
                
              }
             
               break;      
             
              
                
                 
              case "Branch 2":
                 
                  pst=conn.prepareStatement(myquery1);
                  rs= pst.executeQuery();
              
             while(rs.next()){
              int bc = rs.getInt("br_code");
              String br_code=String.valueOf(bc);
              String wrk_name=rs.getString("wrk_name");
              String wrk_lname=rs.getString("wrk_lname");
              double ws = rs.getDouble("wrk_salary");
              String wrk_salary=String.valueOf(ws);
              
              
             
             
             
              
              String table1[]={br_code,wrk_name,wrk_lname,wrk_salary};
              mytbl.addRow(table1);
              
              pst=conn.prepareStatement(myquery5);
               rs1=pst.executeQuery();
               if (rs1.next()) {
                
                String expenses = rs1.getString("total_expenses");
                jTextField1.setText(expenses);
                jTextField1.setEditable(false);
            } else {
                jTextField1.setText("No data found");
            }
                
             pst=conn.prepareStatement(myquery9);
               rs2=pst.executeQuery();
               if (rs2.next()) {
                
                String totalres = rs2.getString("total_reservations");
                jTextField2.setText(totalres);
                jTextField2.setEditable(false);
            } else {
                jTextField2.setText("No reservations found");
            }
              pst=conn.prepareStatement(myquery13);
               rs3=pst.executeQuery();
               if (rs3.next()) {
                
                String totalres = rs3.getString("total_incomes");
                jTextField3.setText(totalres);
                jTextField3.setEditable(false);
            } else {
                jTextField3.setText("No incomes found");
            } 
             
             
             
             
             
             
             }
             
             
             
              break;
              
             case "Branch 3":
                pst=conn.prepareStatement(myquery2);
                rs= pst.executeQuery();
             
                while(rs.next()){
              int bc = rs.getInt("br_code");
              String br_code=String.valueOf(bc);
              String wrk_name=rs.getString("wrk_name");
              String wrk_lname=rs.getString("wrk_lname");
              double ws = rs.getDouble("wrk_salary");
              String wrk_salary=String.valueOf(ws);
              
              
             
             
             
              
              String table1[]={br_code,wrk_name,wrk_lname,wrk_salary};
              mytbl.addRow(table1);
              
                pst=conn.prepareStatement(myquery6);
               rs1=pst.executeQuery();
               if (rs1.next()) {
                
                String expenses = rs1.getString("total_expenses");
                jTextField1.setText(expenses);
                jTextField1.setEditable(false);
            } else {
                jTextField1.setText("No data found");
            }
                pst=conn.prepareStatement(myquery10);
               rs2=pst.executeQuery();
               if (rs2.next()) {
                
                String totalres = rs2.getString("total_reservations");
                jTextField2.setText(totalres);
                jTextField2.setEditable(false);
            } else {
                jTextField2.setText("No reservations found");
            } 
               
                pst=conn.prepareStatement(myquery14);
               rs3=pst.executeQuery();
               if (rs3.next()) {
                
                String totalres = rs3.getString("total_incomes");
                jTextField3.setText(totalres);
                jTextField3.setEditable(false);
            } else {
                jTextField3.setText("No incomes found");
            } 
                

                
                }
             break;
          
              case "Branch 4":
                pst=conn.prepareStatement(myquery3);
                rs= pst.executeQuery();
         
                while(rs.next()){
              int bc = rs.getInt("br_code");
              String br_code=String.valueOf(bc);
              String wrk_name=rs.getString("wrk_name");
              String wrk_lname=rs.getString("wrk_lname");
              double ws = rs.getDouble("wrk_salary");
              String wrk_salary=String.valueOf(ws);
              
              
             
             
             
              
              String table1[]={br_code,wrk_name,wrk_lname,wrk_salary};
              mytbl.addRow(table1);
              
                
                pst=conn.prepareStatement(myquery7);
               rs1=pst.executeQuery();
               if (rs1.next()) {
                
                String expenses = rs1.getString("total_expenses");
                jTextField1.setText(expenses);
                jTextField1.setEditable(false);
            } else {
                jTextField1.setText("No data found");
            }
              pst=conn.prepareStatement(myquery11);
               rs2=pst.executeQuery();
               if (rs2.next()) {
                
                String totalres = rs2.getString("total_reservations");
                jTextField2.setText(totalres);
                jTextField2.setEditable(false);
            } else {
                jTextField2.setText("No reservations found");
            }   
                 pst=conn.prepareStatement(myquery15);
               rs3=pst.executeQuery();
               if (rs3.next()) {
                
                String totalres = rs3.getString("total_incomes");
                jTextField3.setText(totalres);
                jTextField3.setEditable(false);
            } else {
                jTextField3.setText("No incomes found");
            } 
                
                
                
                
                
                
                
                }
              break;
               
                 
                 
              
               
                    
            
            }
         }
         
             catch(SQLException ex){
             JOptionPane.showMessageDialog(null,ex);  
                    
                     }
        
            
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String str = getUser();
        this.dispose();
        BranchUpdate bu=new BranchUpdate();
        bu.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String str = getUser();
        this.dispose();
        EmployeeUpdate eu=new EmployeeUpdate();
        eu.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BranchMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BranchMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BranchMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BranchMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BranchMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
